# Generated by Django 2.1.4 on 2019-01-05 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=128, verbose_name='出品者ID')),
                ('auth_token', models.CharField(max_length=128, null=True, verbose_name='認証トークン')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API設定(各ユーザ)',
                'verbose_name_plural': 'API設定(各ユーザ)',
                'db_table': 'amazon_api',
            },
        ),
        migrations.CreateModel(
            name='AmazonBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=256, verbose_name='ブランド名')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'amazon_brand',
            },
        ),
        migrations.CreateModel(
            name='AmazonDefaultSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(blank=True, choices=[('New', '新品'), ('Refurbished', '再生品'), ('UsedLikeNew', '中古-ほぼ新品'), ('UsedVeryGood', '中古-非常に良い'), ('UsedGood', '中古-良い'), ('UsedAcceptable', '中古-可'), ('CollectibleLikeNew', 'コレクター商品-ほぼ新品'), ('CollectibleVeryGood', 'コレクター商品-非常に良い'), ('CollectibleGood', 'コレクター商品-良い'), ('CollectibleAcceptable', 'コレクター商品-可')], max_length=32, null=True, verbose_name='コンディション')),
                ('condition_note', models.TextField(blank=True, null=True, verbose_name='コンディション説明')),
                ('part_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='メーカー型番')),
                ('fulfillment_latency', models.IntegerField(blank=True, null=True, verbose_name='リードタイム（日）')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'amazon_default_settings',
            },
        ),
        migrations.CreateModel(
            name='AmazonFeedPriceSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margin_new', models.FloatField(verbose_name='新規出品時の利益設定倍率（仕入れ元価格に対する倍率）')),
                ('margin_offer', models.FloatField(verbose_name='相乗り出品時の利益設定倍率（仕入れ元価格に対する倍率）')),
                ('margin_new_url', models.IntegerField(null=True, verbose_name='金額（円）')),
                ('margin_offer_url', models.IntegerField(null=True, verbose_name='最低利益額（円）')),
                ('offset_offer_price_url', models.IntegerField(null=True, verbose_name='相乗り販売価格（円）')),
                ('lowest_offer_price_url', models.IntegerField(null=True, verbose_name='最低販売価格（円）')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'amazon_feed_price_settings',
            },
        ),
        migrations.CreateModel(
            name='AmazonHobbiesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(db_index=True, verbose_name='表示順序')),
                ('name', models.CharField(max_length=256, verbose_name='名称')),
                ('format', models.CharField(max_length=64, verbose_name='フォーマット')),
                ('feed_product_type', models.CharField(max_length=64, verbose_name='商品タイプ')),
                ('value', models.CharField(db_index=True, max_length=64, verbose_name='推奨ブラウズノード')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': '詳細カテゴリー設定(ホビー)',
                'verbose_name_plural': '詳細カテゴリー設定(ホビー)',
                'db_table': 'amazon_hobbies_category',
            },
        ),
        migrations.CreateModel(
            name='AmazonHobbiesCategoryUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(db_index=True, verbose_name='表示順序')),
                ('name', models.CharField(max_length=256, verbose_name='名称')),
                ('format', models.CharField(max_length=64, verbose_name='フォーマット')),
                ('feed_product_type', models.CharField(max_length=64, verbose_name='商品タイプ')),
                ('value', models.CharField(max_length=64, verbose_name='推奨ブラウズノード')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'amazon_hobbies_category_user',
            },
        ),
        migrations.CreateModel(
            name='AmazonParentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(db_index=True, verbose_name='表示順序')),
                ('name', models.CharField(max_length=256, verbose_name='名称')),
                ('value', models.CharField(max_length=256, verbose_name='値')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': '大カテゴリー設定',
                'verbose_name_plural': '大カテゴリー設定',
                'db_table': 'amazon_parent_category',
            },
        ),
        migrations.CreateModel(
            name='AmazonParentCategoryUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(db_index=True, verbose_name='表示順序')),
                ('name', models.CharField(max_length=256, verbose_name='名称')),
                ('value', models.CharField(db_index=True, max_length=256, verbose_name='値')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'amazon_parent_category_user',
            },
        ),
        migrations.CreateModel(
            name='AmazonPetSuppliesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(db_index=True, verbose_name='表示順序')),
                ('name', models.CharField(max_length=256, verbose_name='名称')),
                ('format', models.CharField(max_length=64, verbose_name='フォーマット')),
                ('feed_product_type', models.CharField(max_length=64, verbose_name='商品タイプ')),
                ('value', models.CharField(max_length=64, verbose_name='推奨ブラウズノード')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'db_table': 'amazon_pet_supplies_category',
            },
        ),
        migrations.CreateModel(
            name='AmazonPetSuppliesCategoryUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(db_index=True, verbose_name='表示順序')),
                ('name', models.CharField(max_length=256, verbose_name='名称')),
                ('format', models.CharField(max_length=64, verbose_name='フォーマット')),
                ('feed_product_type', models.CharField(max_length=64, verbose_name='商品タイプ')),
                ('value', models.CharField(max_length=64, verbose_name='推奨ブラウズノード')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'amazon_pet_supplies_category_user',
            },
        ),
        migrations.CreateModel(
            name='CSVFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(db_index=True, max_length=64, verbose_name='フォーマット')),
                ('fields', models.IntegerField(verbose_name='フィールド数')),
                ('feed_product_type', models.IntegerField(verbose_name='商品タイプ')),
                ('item_sku', models.IntegerField(verbose_name='出品者SKU')),
                ('brand_name', models.IntegerField(verbose_name='ブランド名')),
                ('item_name', models.IntegerField(verbose_name='商品名')),
                ('external_product_id', models.IntegerField(verbose_name='商品コード(JANコード等)')),
                ('external_product_id_type', models.IntegerField(verbose_name='商品コードのタイプ')),
                ('manufacturer', models.IntegerField(verbose_name='メーカー名')),
                ('recommended_browse_nodes', models.IntegerField(verbose_name='推奨ブラウズノード')),
                ('quantity', models.IntegerField(verbose_name='在庫数')),
                ('standard_price', models.IntegerField(verbose_name='商品の販売価格')),
                ('main_image_url', models.IntegerField(verbose_name='商品メイン画像URL')),
                ('part_number', models.IntegerField(verbose_name='メーカー型番')),
                ('condition_type', models.IntegerField(verbose_name='商品のコンディション')),
                ('condition_note', models.IntegerField(verbose_name='商品のコンディション説明')),
                ('product_description', models.IntegerField(verbose_name='商品説明文')),
                ('bullet_point', models.IntegerField(verbose_name='商品の仕様')),
                ('generic_keywords', models.IntegerField(verbose_name='検索キーワード')),
                ('other_image_url1', models.IntegerField(verbose_name='商品サブ画像URL1')),
                ('other_image_url2', models.IntegerField(verbose_name='商品サブ画像URL2')),
                ('other_image_url3', models.IntegerField(verbose_name='商品サブ画像URL3')),
                ('fulfillment_latency', models.IntegerField(verbose_name='リードタイム(出荷までにかかる作業日数)')),
                ('standard_price_points', models.IntegerField(verbose_name='ポイント')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': '新規出品用CSVフォーマット',
                'verbose_name_plural': '新規出品用CSVフォーマット',
                'db_table': 'amazon_csv_format',
            },
        ),
        migrations.CreateModel(
            name='ExcludeAsin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=16, verbose_name='禁止ASIN')),
                ('memo', models.CharField(blank=True, max_length=256, null=True, verbose_name='メモ')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '禁止ASIN',
                'verbose_name_plural': '禁止ASIN',
                'db_table': 'amazon_exclude_asin',
            },
        ),
        migrations.CreateModel(
            name='ExcludeAsinMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=16, verbose_name='禁止ASIN')),
            ],
            options={
                'verbose_name': '禁止ASIN',
                'verbose_name_plural': '禁止ASIN',
                'db_table': 'amazon_exclude_asin_master',
            },
        ),
    ]
