# Generated by Django 2.1.4 on 2019-12-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_amazon', '0002_amazondefaultsettings_standard_price_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonfeedpricesettings',
            name='default_minimum_item_price',
            field=models.IntegerField(default=3000, null=True, verbose_name='新規出品時の最低販売価格(円)'),
        ),
    ]
