# Generated by Django 2.1.4 on 2020-02-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_amazon', '0003_amazonfeedpricesettings_default_minimum_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvformat',
            name='is_adult_product',
            field=models.IntegerField(default=85, verbose_name='アダルト商品'),
        ),
    ]
