# Generated by Django 2.1.4 on 2020-02-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_amazon', '0004_csvformat_is_adult_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazondefaultsettings',
            name='new_auto_item_points',
            field=models.IntegerField(blank=True, null=True, verbose_name='ポイント(新規出品自動化)'),
        ),
        migrations.AddField(
            model_name='amazondefaultsettings',
            name='new_item_points',
            field=models.IntegerField(blank=True, null=True, verbose_name='ポイント(新規出品)'),
        ),
        migrations.AddField(
            model_name='amazondefaultsettings',
            name='ride_item_points',
            field=models.IntegerField(blank=True, null=True, verbose_name='ポイント(相乗り出品)'),
        ),
        migrations.AlterField(
            model_name='amazondefaultsettings',
            name='standard_price_points',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ポイント(デフォルト値)'),
        ),
    ]
