# Generated by Django 2.1.4 on 2020-02-12 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_amazon', '0005_auto_20200205_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excludeasin',
            options={'verbose_name': '禁止ASIN個別設定', 'verbose_name_plural': '禁止ASIN個別設定'},
        ),
        migrations.AlterModelOptions(
            name='excludeasinmaster',
            options={'verbose_name': '新規ユーザー禁止ASINマスタ', 'verbose_name_plural': '新規ユーザー禁止ASINマスタ'},
        ),
    ]
