# Generated by Django 2.1.4 on 2020-07-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_amazon', '0006_auto_20200212_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonapi',
            name='validated_date',
            field=models.DateTimeField(null=True, verbose_name='検証日時'),
        ),
    ]
