# Generated by Django 2.1.4 on 2020-10-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_amazon', '0007_amazonapi_validated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonfeedpricesettings',
            name='margin_offer_percent_url',
            field=models.FloatField(
                default=0, null=True, verbose_name="最低利益率（円）"),
        ),
    ]
