# Generated by Django 2.1.4 on 2019-01-05 15:45

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='氏名')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('max_items', models.IntegerField(blank=True, choices=[(20000, '2万件'), (40000, '4万件'), (50000, '5万件'), (10, '10件(試験用)')], null=True, verbose_name='最大登録商品数')),
                ('check_times', models.IntegerField(blank=True, choices=[(2, '2回/日'), (4, '4回/日')], null=True, verbose_name='在庫チェック回数')),
                ('ip_address', models.TextField(blank=True, help_text='2回/日の場合:<br>2万件:1IP/4万件:2IP/5万件:3IP<br>4回/日の場合:<br>2万件:2IP/4万件:4IP/5万件:5IP', null=True, verbose_name='IPアドレス')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'accounts_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OfferReserchWatcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_type', models.IntegerField(verbose_name='検索種別')),
                ('status', models.IntegerField(verbose_name='ステータス')),
                ('total', models.IntegerField(verbose_name='総検索数')),
                ('exclude_asin', models.IntegerField(verbose_name='出品禁止商品')),
                ('exclude_seller', models.IntegerField(verbose_name='禁止セラー')),
                ('prime', models.IntegerField(verbose_name='PRIME除外件数')),
                ('condition_different', models.IntegerField(verbose_name='検索条件不一致')),
                ('not_found', models.IntegerField(verbose_name='検索結果未該当')),
                ('feed_item', models.IntegerField(verbose_name='相乗り出品商品')),
                ('is_over_items', models.BooleanField(blank=True, null=True, verbose_name='登録商品超過')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='終了日時')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='開始日時')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
            options={
                'verbose_name': '一括相乗り検索モニター',
                'verbose_name_plural': '一括相乗り検索モニター',
                'db_table': 'offer_reserch_watcher',
            },
        ),
        migrations.CreateModel(
            name='StopRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.IntegerField(verbose_name='停止対象画面')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
            options={
                'verbose_name': '一括相乗り検索停止要求',
                'verbose_name_plural': '一括相乗り検索停止要求',
                'db_table': 'stop_request',
            },
        ),
    ]
