# Generated by Django 2.1.4 on 2019-01-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='update_mercari_to_amazon_feed_pid',
            field=models.IntegerField(blank=True, null=True, verbose_name='出品情報更新プロセスPID(メルカリ)'),
        ),
        migrations.AddField(
            model_name='user',
            name='update_mercari_to_amazon_feed_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='出品情報更新プロセス開始時間(メルカリ)'),
        ),
        migrations.AddField(
            model_name='user',
            name='update_yahoo_to_amazon_feed_pid',
            field=models.IntegerField(blank=True, null=True, verbose_name='出品情報更新プロセスPID(ヤフー)'),
        ),
        migrations.AddField(
            model_name='user',
            name='update_yahoo_to_amazon_feed_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='出品情報更新プロセス開始時間(ヤフー)'),
        ),
    ]
