# Generated by Django 2.1.4 on 2019-10-19 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bannedkeyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=64, unique=True, verbose_name='バッチID')),
                ('batch_type', models.CharField(max_length=256, verbose_name='バッチ種別')),
                ('status', models.IntegerField(verbose_name='バッチステータス')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='開始日時')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='StockCheckStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_item_id', models.CharField(max_length=32, verbose_name='アイテム固有ID')),
                ('item_type', models.IntegerField(verbose_name='アイテム種別')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='開始日時')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所有ユーザ')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='stockcheckstatus',
            unique_together={('purchase_item_id', 'item_type', 'owner')},
        ),
    ]
