# Generated by Django 2.1.4 on 2019-11-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191019_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerreserchwatcher',
            name='new_feed_item_candidate',
            field=models.IntegerField(default=0, verbose_name='新規出品候補商品'),
        ),
    ]
