# Generated by Django 2.1.4 on 2019-11-21 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_offerreserchwatcher_new_feed_item_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCandidateToCsv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_output_yahoo', models.IntegerField(default=0, verbose_name='今日出力したYahooアイテム数')),
                ('today_output_mercari', models.IntegerField(default=0, verbose_name='今日出力したMercariアイテム数')),
                ('max_output_yahoo', models.IntegerField(default=0, verbose_name='1日に出力可能な最大Yahooアイテム数')),
                ('max_output_mercari', models.IntegerField(default=0, verbose_name='1日に出力可能な最大Mercariアイテム数')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='開始日時')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所有ユーザ')),
            ],
            options={
                'verbose_name': '相乗り/新規出品制御',
                'verbose_name_plural': '相乗り/新規出品制御',
            },
        ),
    ]
