# Generated by Django 2.1.4 on 2019-11-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191126_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='overrideconstantvalue',
            name='description',
            field=models.CharField(default='', max_length=1024, null=True, verbose_name='説明'),
        ),
    ]
