# Generated by Django 2.1.4 on 2019-12-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_overrideconstantvalue_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemNameFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('replace', '単純置換'), ('regex', '正規表現置換')], max_length=32, verbose_name='修正手段')),
                ('from_text', models.CharField(max_length=256, verbose_name='検索文')),
                ('to_text', models.CharField(blank=True, max_length=256, null=True, verbose_name='置換文')),
                ('comment', models.CharField(blank=True, max_length=256, null=True, verbose_name='コメント')),
                ('priority', models.IntegerField(verbose_name='適用優先順位(大きい方が先)')),
                ('valid', models.IntegerField(verbose_name='有効無効')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='開始日時')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='itemnameformat',
            unique_together={('strategy', 'from_text', 'priority')},
        ),
    ]
