# Generated by Django 2.1.4 on 2020-01-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20191209_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='FJCMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=128, verbose_name='出品者ID')),
                ('username', models.CharField(max_length=128, verbose_name='ユーザー名')),
                ('url', models.CharField(max_length=512, verbose_name='取得元URL')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='開始日時')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'FJCメンバー管理',
                'verbose_name_plural': 'FCJメンバー管理',
            },
        ),
    ]
