# Generated by Django 2.1.4 on 2020-06-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_urlskiprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundsearchinfo',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='検索終了日時'),
        ),
        migrations.AddField(
            model_name='backgroundsearchinfo',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='検索開始日時'),
        ),
        migrations.AddField(
            model_name='backgroundsearchinfo',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時'),
        ),
    ]
