# Generated by Django 2.1.4 on 2019-11-26 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mercari', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercariToAmazonItemCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.IntegerField(null=True, verbose_name='出品種別')),
                ('item_sku', models.CharField(db_index=True, max_length=64, null=True, verbose_name='出品者SKU')),
                ('item_name', models.CharField(db_index=True, max_length=256, null=True, verbose_name='商品名')),
                ('external_product_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='商品コード(JANコード等)')),
                ('external_product_id_type', models.CharField(blank=True, choices=[('EAN', 'EAN'), ('ISBN', 'ISBN'), ('UPC', 'UPC'), ('ASIN', 'ASIN'), ('GTIN', 'GTIN')], max_length=16, null=True, verbose_name='商品コードのタイプ')),
                ('brand_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='ブランド名')),
                ('manufacturer', models.CharField(blank=True, max_length=256, null=True, verbose_name='メーカー名')),
                ('feed_product_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='商品タイプ')),
                ('part_number', models.CharField(blank=True, max_length=256, null=True, verbose_name='メーカー型番')),
                ('product_description', models.TextField(blank=True, null=True, verbose_name='商品説明文')),
                ('bullet_point', models.TextField(blank=True, null=True, verbose_name='商品の仕様')),
                ('model', models.CharField(blank=True, max_length=256, null=True, verbose_name='型番')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='在庫数(登録時)')),
                ('fulfillment_latency', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='リードタイム(登録時)')),
                ('condition_type', models.CharField(blank=True, choices=[('New', '新品'), ('Refurbished', '再生品'), ('UsedLikeNew', '中古-ほぼ新品'), ('UsedVeryGood', '中古-非常に良い'), ('UsedGood', '中古-良い'), ('UsedAcceptable', '中古-可'), ('CollectibleLikeNew', 'コレクター商品-ほぼ新品'), ('CollectibleVeryGood', 'コレクター商品-非常に良い'), ('CollectibleGood', 'コレクター商品-良い'), ('CollectibleAcceptable', 'コレクター商品-可')], max_length=32, null=True, verbose_name='商品のコンディション')),
                ('standard_price', models.IntegerField(null=True, verbose_name='商品の販売価格')),
                ('standard_price_points', models.IntegerField(blank=True, null=True, verbose_name='ポイント')),
                ('condition_note', models.TextField(null=True, verbose_name='商品のコンディション説明')),
                ('item_weight', models.IntegerField(blank=True, null=True, verbose_name='商品の重量')),
                ('item_weight_unit_of_measure', models.CharField(blank=True, max_length=16, null=True, verbose_name='商品の重量の単位')),
                ('item_height', models.IntegerField(blank=True, null=True, verbose_name='商品の高さ')),
                ('item_length', models.IntegerField(blank=True, null=True, verbose_name='商品の長さ')),
                ('item_width', models.IntegerField(blank=True, null=True, verbose_name='商品の幅')),
                ('item_length_unit_of_measure', models.CharField(blank=True, max_length=16, null=True, verbose_name='商品寸法の単位')),
                ('recommended_browse_nodes', models.CharField(blank=True, max_length=64, null=True, verbose_name='推奨ブラウズノード')),
                ('generic_keywords', models.CharField(blank=True, max_length=256, null=True, verbose_name='検索キーワード')),
                ('main_image_url', models.CharField(max_length=256, null=True, verbose_name='商品メイン画像URL')),
                ('other_image_url1', models.CharField(blank=True, max_length=256, null=True, verbose_name='商品サブ画像URL1')),
                ('other_image_url2', models.CharField(blank=True, max_length=256, null=True, verbose_name='商品サブ画像URL2')),
                ('other_image_url3', models.CharField(blank=True, max_length=256, null=True, verbose_name='商品サブ画像URL3')),
                ('csv_flag', models.IntegerField(db_index=True, null=True, verbose_name='CSV出力状態')),
                ('format', models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='フォーマット')),
                ('category', models.CharField(blank=True, max_length=32, null=True, verbose_name='カテゴリー')),
                ('purchaseo_seller_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='セーラーID(登録時)')),
                ('purchaseo_seller_id_name', models.CharField(max_length=64, null=True, verbose_name='セラー名(登録時)')),
                ('purchase_item_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='商品ID(登録時)')),
                ('purchase_quantity', models.IntegerField(blank=True, null=True, verbose_name='仕入数(登録時)')),
                ('purchase_fulfillment_latency', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='リードタイム(登録時)')),
                ('purchase_price', models.IntegerField(blank=True, null=True, verbose_name='仕入れ価格(登録時)')),
                ('purchase_similarity', models.FloatField(blank=True, null=True, verbose_name='類似度(登録時)')),
                ('current_purchase_seller_id', models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='セーラーID(現在)')),
                ('current_purchase_seller_id_name', models.CharField(db_index=True, max_length=32, null=True, verbose_name='セラー名(現在)')),
                ('current_purchase_item_id', models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='商品ID(現在)')),
                ('current_purchase_quantity', models.IntegerField(blank=True, null=True, verbose_name='仕入数(現在)')),
                ('current_purchase_fulfillment_latency', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='リードタイム(現在)')),
                ('current_purchase_price', models.IntegerField(blank=True, null=True, verbose_name='仕入れ価格(現在)')),
                ('current_similarity', models.FloatField(blank=True, null=True, verbose_name='類似度(現在)')),
                ('amazon_price', models.IntegerField(blank=True, null=True, verbose_name='アマゾン最安値(登録時)')),
                ('update_fulfillment_latency_request', models.BooleanField(blank=True, db_index=True, null=True, verbose_name='リードタイム更新要求')),
                ('research_request', models.BooleanField(blank=True, db_index=True, null=True, verbose_name='在庫検索要求')),
                ('update_quantity_request', models.BooleanField(blank=True, db_index=True, null=True, verbose_name='在庫更新要求')),
                ('record_type', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='レコードタイプ')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ名')),
            ],
            options={
                'db_table': 'mercari_to_amazon_item_candidate',
            },
        ),
    ]
